name: udagram-api-user
on:
  push:
    branches: [ main ]
    paths:
      - udagram-api-user/**
  pull_request:
    branches: [ main ]
jobs:
  udagram-api-user:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push api user
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:udagram-api-user"
          push: true
          tags: locnt210920/udagram-api-user:v2

        