name: simple-node
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: move out
        run: cd ..
      - name: Build and push front-end
        uses: docker/build-push-action@v4
        with:
          context: udagram-frontend
          file: Dockerfile
          push: true
          tags: locnt210920/udagram-frontend


        