# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: simple-node
on:
  push:
    branches: [ udagram-frontend ]
  pull_request:
    branches: [ udagram-frontend ]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: test
        run: ls
      - name: Build and push front-end
        uses: docker/build-push-action@v4
        with:
          context: udagram-frontend
          file: Dockerfile
          push: true
          tags: locnt210920/udagram-frontend


        