# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: simple-node
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls
      - name: cd 
        run: cd ..
      - name: ls
        run: ls
      - name: cd
        run: cd ..
      - name: ls
        run: ls

        